### ISSUE TITLE
4swordshax isnt working

### ISSUE THREAD

**Issue by Enovale** [yellows8/3ds_dsiwarehax_installer#8]
So im on 11.2, I launched fasthax, then installed 4swordhax, then i exited the launcher and opened 4swords. it just shows a white screen and i cant do anything other than exit to home menu. what happened? my only theorys is 1: fasthax doesnt give the proper permissions 2: i didnt make a previous save file in the game

**Comment by fincs** [comment]
4swordshax's NDS loader stub hasn't yet been updated to support binaries compiled with devkitARM r46 (possessing proper TWL headers and ARM9i/ARM7i binaries). The other dsiwarehax savefiles are not affected because their codebase is different and it has always supported such binaries. I'll look into fixing this.

**Comment by Enovale** [comment]
thanks 👍
